pipeline {
    agent any 

    stages {
        stage('Checkout') {
            steps { 
                // Specify the branch to checkout
                git branch: 'main', credentialsId: 'gianniskourentzis', url: 'https://github.com/Gianniskourentzis/jenkinsTestRepo.git'
            }
        }
        
        stage('Build and Run with Docker Compose') {
            steps {
                script { 
                    // Pull the latest images and build the containers
                    sh 'docker-compose pull'
                    sh 'docker-compose up -d --build'
                }
            }
        }
    }

    post {
        always {
            // Optional: Bring down the Docker Compose setup after the build
            sh 'docker-compose down'
        }
    }
}
