pipeline {
    agent any 

    stages {
        stage('Checkout') {
            steps { 
                git credentialsId: 'gianniskourentzis', url: 'https://github.com/Gianniskourentzis/jenkinsTestRepo.git'

            }
        }
        
        stage('Build and Run with Docker Compose') {
            steps {
                script { 
                    sh 'docker compose pull '
                    sh 'docker compose up -d '
                }
            }
        }
    }

    
}
